# Generated by Django 4.2.5 on 2023-09-28 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введите дату матча')),
                ('home_team_score', models.IntegerField(default=0, help_text='Введите счет хозяев', validators=[django.core.validators.MinValueValidator(0)])),
                ('away_team_score', models.IntegerField(default=0, help_text='Введите счет гостей', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(help_text='Введите имя игрока', max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], help_text='Позиция игрока', max_length=50)),
                ('jersey_number', models.IntegerField(default=1, help_text='Введите номер на его майке', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(help_text='Введите название команды', max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(help_text='Из какого города команда', max_length=100)),
                ('conference', models.CharField(choices=[('WEST', 'Western'), ('EAST', 'Eastern')], help_text='Название конференции', max_length=50)),
                ('division', models.CharField(blank=True, help_text='Название дивизиона', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Введите количество очков', validators=[django.core.validators.MinValueValidator(0)])),
                ('rebounds', models.IntegerField(default=0, help_text='Введите количество подборов', validators=[django.core.validators.MinValueValidator(0)])),
                ('assists', models.IntegerField(default=0, help_text='Введите количество передач', validators=[django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(help_text='Выберите игру', on_delete=django.db.models.deletion.CASCADE, to='myApp.game')),
                ('player', models.ForeignKey(help_text='Выберите игрока', on_delete=django.db.models.deletion.CASCADE, to='myApp.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Выберите команду', on_delete=django.db.models.deletion.CASCADE, to='myApp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(help_text='Выберите "гостей" матча', on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='myApp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(help_text='Выберите "хозяев" матча', on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='myApp.team'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number')},
        ),
    ]
