# Generated by Django 4.2.5 on 2023-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
