# Generated by Django 4.2.5 on 2023-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='players',
            field=models.ManyToManyField(related_name='players', to='myApp.player'),
        ),
    ]
