# Generated by Django 4.2.5 on 2023-10-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_id_student_player_id_user_team_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id_user',
        ),
    ]
