# Generated by Django 4.2.5 on 2023-11-02 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_player_id_user_team_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(default=0, help_text='Введите счет гостей', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.IntegerField(default=0, help_text='Введите счет хозяев', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='assists',
            field=models.IntegerField(default=0, help_text='Введите количество передач', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='points',
            field=models.IntegerField(default=0, help_text='Введите количество очков', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='rebounds',
            field=models.IntegerField(default=0, help_text='Введите количество подборов', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
